---
- name: Ensure repository ansibletestrepo1 exists
  infra.quay_configuration.quay_repository:
    name: ansibletestorg/ansibletestrepo1
    repo_state: MIRROR
    visibility: private
    perms:
      - name: ansibletestorg+ansibletestrobot1
        type: user
        role: admin
    state: present
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: ERROR EXPECTED Missing required parameters
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    sync_interval: 43200
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (missing parameters)

- name: ERROR EXPECTED Access to another user namespace
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestuser1/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: 43200
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (not allowed)

- name: Ensure repository mirror configuration for ansibletestrepo1 exists
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: 43200
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Ensure repository mirror configutation is updated (no change)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    http_proxy: ""
    verify_tls: true
    sync_interval: 12h
    image_tags:
      - latest
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  register: result

- name: Ensure that the task did not change anything
  ansible.builtin.assert:
    that: not result['changed']
    fail_msg: The preceding task should not have changed anything

- name: Ensure repository mirror configuration is updated (1)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    http_proxy: http://proxy.example.com:3128
    sync_interval: 21600
    image_tags:
      - linux
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Ensure repository mirror configuration is updated (2)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    https_proxy: https://proxy.example.com:3128
    http_proxy: ""
    no_proxy: quay.io
    verify_tls: false
    sync_interval: 360m
    image_tags:
      - linux
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Ensure repository mirror configuration is updated (3)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    https_proxy: ""
    http_proxy: ""
    no_proxy: ""
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Ensure repository mirror configuration is updated (4)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    https_proxy: https://proxy.example.com:3128
    http_proxy: ""
    no_proxy: quay.io
    external_registry_username: jziglar
    external_registry_password: vs9mrD55NP
    verify_tls: false
    sync_interval: 21600s
    sync_start_date: "2021-11-02T21:42:00Z"
    image_tags:
      - linux
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Ensure repository mirror conf for ansibletestrepo1 is active
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    is_enabled: true
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: Force repository mirror configuration for ansibletestrepo1 to sync
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    force_sync: true
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false

- name: ERROR EXPECTED Wrong sync interval
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestorg/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: notaninterval
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (wrong sync interval)

- name: ERROR EXPECTED Non-existing repository (1)
  infra.quay_configuration.quay_repository_mirror:
    name: nonexisting/ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: 4d
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (non-existing repository)

- name: ERROR EXPECTED Non-existing repository (2)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: 4w
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (non-existing repository)

- name: ERROR EXPECTED Non-existing repository (anonymous)
  infra.quay_configuration.quay_repository_mirror:
    name: ansibletestrepo1
    external_reference: docker.io/library/hello-world
    robot_username: ansibletestorg+ansibletestrobot1
    image_tags:
      - latest
    sync_interval: 43200
    sync_start_date: "2021-01-01T12:00:00Z"
    quay_host: quay.io
    validate_certs: false
  ignore_errors: true
  register: result

- name: Ensure that the task failed
  ansible.builtin.assert:
    that: result['failed']
    fail_msg: The preceding task should have failed (non-existing repository)

- name: Ensure repository ansibletestrepo1 is removed
  infra.quay_configuration.quay_repository:
    name: ansibletestorg/ansibletestrepo1
    state: absent
    quay_host: "{{ quay_url }}"
    quay_token: "{{ quay_token }}"
    validate_certs: false
...
